services:
  db:
    image: postgres:16
    container_name: veriproof-db
    environment:
      POSTGRES_DB: veriproof
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oracle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
